### PR TITLE
Remove mentions of beta for table endpoints

### PR DESCRIPTION
**Pull request by a-monteiro**
Fixes PRO-1137

To merge on GA

### CODE REVIEW

**Comment by a-monteiro** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/duneanalytics/dune-api-docs/100?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#100** <a href="https://app.graphite.dev/github/pr/duneanalytics/dune-api-docs/100?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#99** <a href="https://app.graphite.dev/github/pr/duneanalytics/dune-api-docs/99?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @a-monteiro and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by hawkaa — APPROVED** [review]
🚀 

Even though we won't announce anything before 🌊 3 on April 12th, I don't see a problem fixing this documentation already. We are unlikely to make any breaking changes.

**Review by helanto — COMMENTED** [review]
Should we deprecate the CSV uploads endpoint ?

**Comment by hawkaa** [comment]
> Should we deprecate the CSV uploads endpoint ?

No plans of deprecation, at least not yet. @vegarsti added a helpful message:

Screenshot 2024-04-04 at 08 16 34

**Comment by helanto** [comment]
> > Should we deprecate the CSV uploads endpoint ?
> 
> No plans of deprecation, at least not yet. @vegarsti added a helpful message:
> 
> Screenshot 2024-04-04 at 08 16 34

So we want the infer schema flexibility the other endpoint offers ? I can imagine that eventually we want to move away from it, just one other service to maintain.

**Comment by hawkaa** [comment]
> So we want the infer schema flexibility the other endpoint offers ? I can imagine that eventually we want to move away from it, just one other service to maintain.

Good point. If we want to move away from this, we should deprecate it as soon as possible to avoid new users start using it. I am however not comfortable doing that right now given our priorities for Q2. We might not be able to add the infer functionality for a while.

**Pull request merged**
