### PR TITLE
Change the messaging on the CSV upload endpoint related to other endpoints

### PR DESCRIPTION
**Pull request by vegarsti**
As per report on Slack
Screenshot 2024-03-21 at 09 18 35

### CODE REVIEW

**Comment by vegarsti** [comment]
* **#78** <a href="https://app.graphite.dev/github/pr/duneanalytics/dune-api-docs/78?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @vegarsti and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by hawkaa — CHANGES_REQUESTED** [review]
Is it deprecated? I didn't know this.

**Comment by vegarsti** [comment]
> Is it deprecated? I didn't know this.

Right. Maybe deprecated isn't the right word, either. Do you have a suggestion for how to make this clearer?

**Comment by hawkaa** [comment]
> > Is it deprecated? I didn't know this.
> 
> Right. Maybe deprecated isn't the right word, either. Do you have a suggestion for how to make this clearer?

Maybe something alas "Consider using the create/ and insert/ endpoints if you want more flexibility, performance, and the ability to append."?

**Comment by vegarsti** [comment]
> > > Is it deprecated? I didn't know this.
> > 
> > 
> > Right. Maybe deprecated isn't the right word, either. Do you have a suggestion for how to make this clearer?
> 
> Maybe something alas "Consider using the create/ and insert/ endpoints if you want more flexibility, performance, and the ability to append."?

Good, thanks!

**Review by hawkaa — APPROVED** [review]

**Pull request merged**
